### ISSUE TITLE
Fix auto scroll for new step

### ISSUE THREAD

**Issue by phreic** [LumPenPacK/NetworkExtractionFromImages#24]

**Comment by gdenn** [comment]
![capture](https://cloud.githubusercontent.com/assets/9344404/13547869/541ca682-e2e2-11e5-8da9-fdb3868765c6.PNG)
We should also correct the layout of the steps. They are a little bit off.

**Comment by gdenn** [comment]
I created an margin around that up_down button widget to position correctly:
pip_up_down.setContentsMargins(0,-15,0,0)
![capture](https://cloud.githubusercontent.com/assets/9344404/13548034/2d8c1f62-e2e6-11e5-8484-3f120c540411.PNG)

**Comment by gdenn** [comment]
We need to set the maximum length of the labels. maybe we should just tell which algorithm is selected.
For Dialation Erorosion it will collide otherwise.
