### ISSUE TITLE
Left panel after recalculation displays incorrect results

### ISSUE THREAD

**Issue by tastyminerals** [LumPenPacK/NetworkExtractionFromImages#36]
When the pipeline is recalculated only the result of the modified algorithm is added to the left panel while the results of the rest of the algorithms are not added.
You need to replace the images processed by the previous algorithms and explicitly call update_cache() .

**Comment by gdenn** [comment]
So we solved it the way that we have an clear button on the left panel. The images get rendered in the left panel until the user decides to remove them with the button.
This way, the user is able to compare results
