### ISSUE TITLE
Installation package for windows

### ISSUE THREAD

**Issue by gdenn** [LumPenPacK/NetworkExtractionFromImages#46]
We need a installation package for at least Win64. This can be a python wheel e.g. which can be invoked by the setup.py of the python project.

It would be great if we can create packages for debian and MacOS too, but i guess thats optional

**Comment by tastyminerals** [comment]
For Windows, definitely.

Creating a Debian package requires a lot of time. Maybe somebody from Debian community will do this job. Same thing with other Linux distros. 
I don't have any knowledge about the amount of work and time required to build one for MacOS.

For a python project it is enough to have **setup.py**, the rest is up to the user and distro maintainers.

**Comment by phreic** [comment]
I don't think we need an installer for Windows anymore. A simple zip file should be enough.

**Comment by tastyminerals** [comment]
Installer version can add a start icon as well as uninstaller. 
Various projects usually provide both variants, portable (zip) and installer.
